# Generated by Django 6.0.2 on 2026-02-06 04:16

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف المستخدم')),
                ('phone_number', models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بالصيغة: +999999999. حتى 15 رقم مسموح.', regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('whatsapp_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='معرف واتساب')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='الاسم')),
                ('location', models.JSONField(blank=True, default=dict, help_text='{"lat": 0.0, "lng": 0.0}', verbose_name='الموقع')),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التسجيل')),
                ('last_interaction', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخر تفاعل')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='تفضيلات المستخدم مثل اللغة والإشعارات', verbose_name='التفضيلات')),
            ],
            options={
                'verbose_name': 'مستخدم واتساب',
                'verbose_name_plural': 'مستخدمو واتساب',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['phone_number', 'is_active'], name='users_whats_phone_n_7b48a7_idx'), models.Index(fields=['last_interaction'], name='users_whats_last_in_594dc9_idx')],
            },
        ),
    ]
