# Generated by Django 5.2.6 on 2026-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='customer_category',
            field=models.CharField(choices=[('individual', 'فرد'), ('merchant', 'تاجر / صاحب محل'), ('restaurant', 'مطعم / كافيه'), ('company', 'شركة / مؤسسة'), ('contractor', 'مقاول / فني'), ('other', 'أخرى')], db_index=True, default='individual', help_text='تصنيف العميل لاستهداف الرسائل الدعائية', max_length=20, verbose_name='تصنيف العميل'),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='علامات مخصصة مثل: ["نشط", "قهوة", "مطعم"]', verbose_name='العلامات'),
        ),
    ]
