# Generated by Django 5.2.6 on 2026-04-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_customer_category_tags_agent_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='terms_accepted',
            field=models.BooleanField(db_index=True, default=False, help_text='هل ضغط المستخدم على زر الموافقة على الشروط والأحكام', verbose_name='وافق على الشروط'),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة على الشروط'),
        ),
    ]
