# Generated by Django 6.0.2 on 2026-02-06 04:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('icon', models.CharField(blank=True, help_text='اسم أيقونة Bootstrap Icons', max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='suppliers.category', verbose_name='التصنيف الرئيسي')),
            ],
            options={
                'verbose_name': 'تصنيف فرعي',
                'verbose_name_plural': 'التصنيفات الفرعية',
                'ordering': ['category', 'name_ar'],
                'unique_together': {('category', 'name_ar')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف المورد')),
                ('name_ar', models.CharField(db_index=True, max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('location', models.JSONField(default=dict, help_text='{"lat": 0.0, "lng": 0.0, "address": ""}', verbose_name='الموقع')),
                ('google_maps_place_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='معرف Google Maps')),
                ('phone_numbers', models.JSONField(default=list, help_text='["0501234567", "0551234567"]', verbose_name='أرقام الهواتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('is_partner', models.BooleanField(db_index=True, default=False, help_text='هل المورد شريك رسمي؟', verbose_name='شريك')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='موثق')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='{"saturday": {"open": "08:00", "close": "22:00"}, ...}', verbose_name='ساعات العمل')),
                ('services', models.JSONField(blank=True, default=list, help_text='["خدمة 1", "خدمة 2"]', verbose_name='الخدمات')),
                ('images', models.JSONField(blank=True, default=list, help_text='["url1", "url2"]', verbose_name='الصور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='suppliers.category', verbose_name='التصنيف')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='suppliers.subcategory', verbose_name='التصنيف الفرعي')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['-is_partner', '-rating', 'name_ar'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='suppliers_s_categor_af0ff2_idx'), models.Index(fields=['is_partner', 'is_active'], name='suppliers_s_is_part_946545_idx'), models.Index(fields=['rating'], name='suppliers_s_rating_8cb116_idx'), models.Index(fields=['name_ar'], name='suppliers_s_name_ar_c692ba_idx')],
            },
        ),
    ]
