# Generated by Django 6.0.2 on 2026-02-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='رابط الموقع على خرائط جوجل', max_length=500, verbose_name='رابط Google Maps'),
        ),
    ]
