# Generated by Django 5.2.6 on 2026-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_add_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='agent_notes',
            field=models.TextField(blank=True, help_text='ملاحظات خاصة يقرأها الوكيل عند اقتراح هذا المحل (مثال: متخصص في وجبات عائلية، يوفر توصيل)', verbose_name='ملاحظات الوكيل'),
        ),
    ]
