# Generated by Django 5.2.6 on 2026-04-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_add_customer_category_tags_agent_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
            ],
            options={
                'verbose_name': 'شريك معتمد',
                'verbose_name_plural': 'الشركاء المعتمدون',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('suppliers.supplier',),
        ),
    ]
