# Generated by Django 6.0.2 on 2026-02-06 04:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف الطلب')),
                ('location_requested', models.JSONField(blank=True, default=dict, help_text='{"lat": 0.0, "lng": 0.0, "address": ""}', verbose_name='الموقع المطلوب')),
                ('search_query', models.CharField(blank=True, max_length=500, verbose_name='نص البحث')),
                ('suppliers_suggested', models.JSONField(blank=True, default=list, help_text='["supplier_id_1", "supplier_id_2"]', verbose_name='الموردون المقترحون')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='وقت الاستجابة (مللي ثانية)')),
                ('user_feedback', models.JSONField(blank=True, default=dict, help_text='{"rating": 5, "comment": "..."}', verbose_name='ملاحظات المستخدم')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='suppliers.category', verbose_name='التصنيف')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='conversations.conversation', verbose_name='المحادثة')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='suppliers.subcategory', verbose_name='التصنيف الفرعي')),
                ('supplier_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_requests', to='suppliers.supplier', verbose_name='المورد المختار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.whatsappuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='requests_se_user_id_b4032b_idx'), models.Index(fields=['category', 'status'], name='requests_se_categor_3da0ca_idx'), models.Index(fields=['status', 'timestamp'], name='requests_se_status_c390f9_idx')],
            },
        ),
    ]
