# Generated by Django 6.0.2 on 2026-02-06 04:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف المحادثة')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='بداية المحادثة')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية المحادثة')),
                ('messages', models.JSONField(default=list, help_text='[{"role": "user/bot", "content": "...", "timestamp": "..."}]', verbose_name='الرسائل')),
                ('intent_detected', models.CharField(choices=[('search', 'بحث'), ('inquiry', 'استفسار'), ('complaint', 'شكوى'), ('feedback', 'ملاحظات'), ('booking', 'حجز'), ('other', 'أخرى')], db_index=True, default='other', max_length=20, verbose_name='النية المكتشفة')),
                ('sentiment_score', models.DecimalField(decimal_places=3, default=0.0, help_text='-1.0 سلبي إلى 1.0 إيجابي', max_digits=4, verbose_name='درجة المشاعر')),
                ('resolved', models.BooleanField(db_index=True, default=False, verbose_name='تم الحل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.whatsappuser', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='conversatio_user_id_03cf5c_idx'), models.Index(fields=['intent_detected', 'resolved'], name='conversatio_intent__d25684_idx')],
            },
        ),
    ]
