# Generated by Django 6.0.2 on 2026-02-06 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='الإعداد الافتراضي', max_length=100, verbose_name='اسم الإعداد')),
                ('is_active', models.BooleanField(default=True, help_text='الإعداد النشط هو المستخدم حاليا', verbose_name='نشط')),
                ('model_name', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini (سريع وموفر)'), ('gpt-4o', 'GPT-4o (أقوى)'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (أرخص)')], default='gpt-4o-mini', max_length=50, verbose_name='نموذج الذكاء الاصطناعي')),
                ('system_prompt', models.TextField(default='أنت "ذيبان"  - وكيل ذكاء اصطناعي ودليل ذكي لمدينة عنيزة في منطقة القصيم بالمملكة العربية السعودية.\n\n## مهمتك:\n- مساعدة المستخدمين في إيجاد أفضل الخدمات والأماكن في عنيزة\n- فهم طلبات المستخدمين بلغتهم الطبيعية\n- البحث في قاعدة بيانات الموردين وتقديم أفضل الخيارات\n- الرد بطريقة ودية ومختصرة\n\n## قواعد الرد:\n1. رد دائما باللغة العربية\n2. كن مختصرا ومفيدا\n3. استخدم الإيموجي بشكل معتدل\n4. قدم معلومات التواصل عند توفرها\n5. إذا لم تجد نتائج اقترح بدائل أو اطلب توضيحا\n\nتذكر: أنت ذيبان الذئب الذكي الذي يعرف كل شيء عن عنيزة! ', help_text='التعليمات الأساسية للوكيل', verbose_name='System Prompt')),
                ('temperature', models.FloatField(default=0.7, help_text='0 = دقيق جدا 1 = إبداعي أكثر', verbose_name='Temperature')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='الحد الأقصى للكلمات')),
                ('welcome_message', models.TextField(default='مرحبا! أنا ذيبان \nدليلك الذكي في عنيزة!\n\nكيف أقدر أساعدك اليوم\n- ابحث لك عن كهربائي سباك نجار...\n- أدلك على أفضل المطاعم والمقاهي\n- أوصلك بأي خدمة تحتاجها\n\nفقط قل لي وش تبي! ', verbose_name='رسالة الترحيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الوكيل',
                'verbose_name_plural': 'إعدادات الوكيل',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
