# Generated by Django 5.2.6 on 2026-04-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsettings',
            name='model_name',
            field=models.CharField(choices=[('gpt-4.1', 'GPT-4.1 (الأحدث والأقوى)'), ('gpt-4o', 'GPT-4o (موصى به)'), ('gpt-4o-mini', 'GPT-4o Mini (سريع وموفر)'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (أرخص)')], default='gpt-4o', max_length=50, verbose_name='نموذج الذكاء الاصطناعي'),
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='system_prompt',
            field=models.TextField(default='', help_text='التعليمات الأساسية للوكيل — ملاحظة: CORE_RULES تُحقن تلقائياً فوق هذا النص ولا يمكن تجاوزها', verbose_name='System Prompt'),
        ),
        migrations.AlterField(
            model_name='agentsettings',
            name='temperature',
            field=models.FloatField(default=0.9, help_text='0 = دقيق جدا 1 = إبداعي أكثر', verbose_name='Temperature'),
        ),
    ]
