# Generated by Django 5.2.6 on 2026-04-16 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_alter_agentsettings_model_name_and_more'),
        ('suppliers', '0004_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_phone', models.CharField(db_index=True, max_length=30, verbose_name='رقم جوال المستخدم')),
                ('context_keyword', models.CharField(blank=True, help_text='الفئة أو الكلمة التي أطلقت الترشيح (مطعم، كافيه، سباك...)', max_length=100, verbose_name='الكلمة/الفئة السياقية')),
                ('user_message', models.TextField(blank=True, help_text='مقتطف من رسالة المستخدم التي أدّت للترشيح', verbose_name='رسالة المستخدم')),
                ('was_clicked', models.BooleanField(default=False, help_text='هل ضغط المستخدم على الرابط أو تواصل لاحقاً؟', verbose_name='تم التفاعل؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت الترشيح')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='suppliers.supplier', verbose_name='الشريك')),
            ],
            options={
                'verbose_name': 'ترشيح شريك',
                'verbose_name_plural': 'ترشيحات الشركاء',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_phone', '-created_at'], name='ai_agent_pa_user_ph_c4c4ad_idx'), models.Index(fields=['partner', '-created_at'], name='ai_agent_pa_partner_f29b36_idx')],
            },
        ),
    ]
